ci:
  autofix_prs: true
  autoupdate_schedule: quarterly
  submodules: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: sort-simple-yaml
        files: .pre-commit-config.yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
  - repo: https://github.com/crate-ci/typos
    rev: typos-v0.10.34
    hooks:
      - id: typos
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.3.0
    hooks:
      - id: zizmor
