name: Publish to PyPI

on:
  release:
    types:
      - created
  workflow_dispatch: # Allows manual triggering
      inputs:
        do-publish:
          description: 'Actually publish to PyPI'
          required: true
          type: boolean
          default: false

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Only read permissions are needed for this job
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ">=3.10"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        uv
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m uv build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish Python distribution to PyPI
    if: github.event_name == 'release' || github.event.inputs.do-publish
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/neuro-api-tony
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
